{% set name = "tranquilo" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tranquilo-{{ version }}.tar.gz
  sha256: 33824f3907c1582cb786a1a6b56d9135fed8ff82359158033099559413ab8741

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=45
    - wheel
    - setuptools-scm >=6.0
    - pip
  run:
    - python >=3.8
    - estimagic >=0.4.2
    - numba
    - numpy >=1.17.0
    - pandas
    - plotly
    - scipy >=1.2.1

test:
  imports:
    - tranquilo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/OpenSourceEconomics/tranquilo
  summary: Trust-region optimizer for scalar, least-square and noisy problems
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - janosg
    - timmens
